INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Mouse', 'Wireless', '149');
INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Mouse B', 'Wireless', '149');
INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Mouse C', 'Wireless', '149');